# Official DTU colors for plots
colors:
  dtu_red: "#990000"
  black: "#000000"
  blue: "#2F3EEA"
  bright_green: "#1FD082"
  navy_blue: "#030F4F"
  yellow: "#F6D04D"
  orange: "#FC7634"
  pink: "#F7BBB1"
  grey: "#DADADA"
  red: "#E83F48"
  green: "#008835"
  purple: "#79238E"

ch_names: ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'Oz', 'O2']
ch_names1: ['Fp1',
 'Fpz',
 'Fp2',
 'F7',
 'F3',
 'Fz',
 'F4',
 'F8',
 'FT7',
 'FC3',
 'FCz',
 'FC4',
 'FT8',
 'T3',
 'C3',
 'Cz',
 'C4',
 'T4',
 'TP7',
 'CP3',
 'CPz',
 'CP4',
 'TP8',
 'T5',
 'P3',
 'Pz',
 'P4',
 'T6',
 'O1',
 'Oz',
 'O2']
preprocess:
  low_cut: 0.5
  high_cut: 70

healthy_subjects: ['S2','S3', 'S9','S10','S12','S13','S14','S15','S19','S20','S24','S25','S30','S32','S38','S39','S42','S46','S29','S6','S23','S47','S49']
depressed_subjects: ['S1','S4','S5','S7','S8','S11','S16','S17','S18','S21','S22','S26','S27','S31','S33','S35','S36','S37','S40','S41','S43','S44','S45']

# Noisy records which should be removed and not used
# S51_post_EC_DepActive_2min removed because it is much shorter than all others (only 100 s after cutting)
noisy_recs: [
    "S1_Pre-EC1_EEG", "S8_Post_EC1_EEG", 'S8-EO1pre_EEG', "S9-post-EC1_EEG",
    "S9-Pre_EC1", "S9-Pre_EO1", "S15_Pre_EC1_EEG",
    "S15_Pre_EO1_EEG", "S18-pre_EC1_EEG", "S18-pre_EO1_EEG", 
    "S25_Post_EC1_EEG", "S25_Post_EO1_EEG", "S24_pre_EO1", "S26_pre_EC1_EEG",
    "S26_pre_EO1_EEG", "S29_EC1_Post_EEG", "S29_EO1Post_EEG", 
    "S33_Post_EC1_EEG", "S33_Post_EO1_EEG", "S35_pre_Ec1_EEG",
    "S35_pre_Eo1_EEG", "S35-PostEC1_EEG", "S35-PostEO1_EEG",
    "S37_EC1_Pre_EEG", "S37_EO1_Pre_EEG", "S39-Post_EC1_EEG",
    "S39-Post_EO1_EEG", "S39_Pre_EC1_EEG", "S39_Pre_EO1_EEG", "S40_EC_Post_EEG",
    "S40_EO1_post_EEG", "S40_EC_Pre_EEG", "S40_EO_pre_EEG", "S41_EC1_post_EEG",
    "S41_EO1_post_EEG", "S41_EC1_pre_EEG", "S42_EC1PostBilal_EEG", "S42_EO1PostBilal",
    "S42_pre_EO1", "S42_Prre_EC1", "S44_EC1_post_EEG", "S44_EO1_post_EEG", "S44_EO1_pre_EEG",
    "S44_EC1_pre_EEG", "S45_EC1_Pre_EEG", "S45_EO1_pre_EEG",
    "S45_Post_EC1_EEG", "S45_Post_EO1_EEG", "S46_EO1_post_EEG",
    "S46_Pre_EC1", "S46_Pre_EO1", "S46_EC1_post_EEG", "S47_pre_EC1_EEG",
    "S47_pre_EO1_EEG", "S52_Pre_EC"
]

channels: [['Fp1', 'Fp2', 'F3','F4', 'F7', 'F8', 'Fpz', 'TP7', 'TP8', 'T5', 'T6',
'P3', 'P4', 'FT7', 'FT8', 'O1', 'O2', 'C3', 'C4']]