wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1667904942.821005
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 16
      - 19
      - 23
      - 24
      4: 3.9.12
      5: 0.13.5
      8:
      - 3
      - 5
      10:
      - 9
magic:
  desc: null
  value:
    enable: true
